<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
<?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

    /* custom_sirena: Extra Classes and helpers */
    $products_wrapper_class = 'products wrapper grid products-grid columns-4';
?>
    <div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
        <?php if ($block->getTitle()): ?>
        <div class="block-title">
            <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
        </div>
        <?php endif ?>
        <div class="block-content">
            <?= /* @escapeNotVerified */ '<!-- ' . $image . '-->' ?>
            <div class="<?php /* @escapeNotVerified */ echo $products_wrapper_class; ?>">
                <ol class="product-items <?= /* @escapeNotVerified */ $type ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php $product_inner_wrapper_class = 'product-item-info';
                        if ( !$_item->isAvailable() ) {
                            $product_inner_wrapper_class .= ' sold-out';
                        } ?>
                        <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>

                        <div class="<?php /* @escapeNotVerified */ echo $product_inner_wrapper_class; ?>">
                            <div class="image-wrapper">
                                <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                                <?php if (!$_item->isAvailable()): ?>
                                    <div class="sold-out-label">
                                        <span><?php /* @escapeNotVerified */ echo __('Sold out') ?></span>
                                    </div>
                                <?php endif; ?>
                            </div>

                            <strong class="product-item-name">
                                <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                   href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>"
                                   class="product-item-link">
                                    <?= $block->escapeHtml($_item->getName()) ?>
                                </a>
                            </strong>

                            <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                                <div class="wishlist-button-wrapper" data-role="add-to-links">
                                    <a href="#"
                                       data-post='<?= /* @escapeNotVerified */ $block->getAddToWishlistParams($_item) ?>'
                                       class="action towishlist" data-action="add-to-wishlist"
                                       title="<?= /* @escapeNotVerified */ __('Add to Wish List') ?>">
                                        <span><?= /* @escapeNotVerified */ __('Add to Wish List') ?></span>
                                    </a>
                                </div>
                            <?php endif; ?>

                            <?php echo $block->getProductPriceHtml($_item, $type); ?>

                            <?php if ($_item->isAvailable()): ?>
                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                            <?php else: ?>
                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                            <?php endif; ?>

                            <?php if ($templateType): ?>
                                <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                            <?php endif; ?>
                            
                            <?= $block->getProductDetailsHtml($_item) ?>

                            <?php if ($showCart): ?>
                                <div class="product-action-wrapper">
                                    <?php if ($_item->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']); ?>" method="post">
                                            <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']); ?>">
                                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary btn-cart">
                                                <i class="meigee-icon-cart"></i><span><?= $block->escapeHtml(__('Add to Cart')); ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <a href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" title="<?php echo __('Read more') ?>" class="btn btn-default btn-cart"><i class="meigee-icon-read-more"></i><span><?php echo __('Read more') ?></span></a>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>

                            <?php if ($showCompare): ?>
                                <div class="secondary-actions-wrapper" data-role="add-to-links">
                                    <?php if ($block->getAddToCompareUrl()): ?>
                                        <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class); ?>
                                        <a href="#" class="action tocompare"
                                           title="<?= /* @escapeNotVerified */ __('Add to Compare') ?>"
                                           data-post='<?= /* @escapeNotVerified */ $compareHelper->getPostDataParams($_item) ?>'>
                                            <i class="meigee-icon-compare"></i>
                                        </a>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                        <?= ($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
