<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */

if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-list';

    $mode = 'list';

    $image = 'new_products_content_widget_list';
    $title = __('New Products');
    $items = $block->getProductCollection()->getItems();
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = true;

    /* custom_sirena: Extra Classes and helpers */
    $products_wrapper_class = 'products wrapper list products-list';
} ?>

<?php if ($exist):?>
    <div class="block widget block-new-products <?= /* @noEscape */ $mode ?>">
        <div class="block-title">
            <strong role="heading" aria-level="2"><?= $block->escapeHtml($title) ?></strong>
        </div>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="<?php /* @escapeNotVerified */ echo $products_wrapper_class; ?>">
                <ol class="product-items list <?= /* @noEscape */ $type ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php $product_inner_wrapper_class = 'product-item-info';
                        if ( !$_item->isAvailable() ) {
                            $product_inner_wrapper_class .= ' sold-out';
                        } ?>
                        <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>

                        <div class="<?php /* @escapeNotVerified */ echo $product_inner_wrapper_class; ?>">
                            <div class="image-wrapper">
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                                <?php if (!$_item->isAvailable()): ?>
                                    <div class="sold-out-label">
                                        <span><?php /* @escapeNotVerified */ echo __('Sold out') ?></span>
                                    </div>
                                <?php endif; ?>
                            </div>

                            <strong class="product-item-name">
                                <a title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                   href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                   class="product-item-link">
                                    <?= $block->escapeHtml($_item->getName()) ?>
                                </a>
                            </strong>

                            <?php if ($this->helper(Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                                <div class="wishlist-button-wrapper" data-role="add-to-links">
                                    <a href="#"
                                       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>'
                                       class="action towishlist" data-action="add-to-wishlist"
                                       title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                    </a>
                                </div>
                            <?php endif; ?>

                            <?php echo $block->getProductPriceHtml($_item, $type); ?>

                            <?php if ($_item->isAvailable()): ?>
                                <div class="stock available"><span><?php $block->escapeHtml(__('In stock')) ?></span></div>
                            <?php else: ?>
                                <div class="stock unavailable"><span><?php $block->escapeHtml(__('Out of stock')) ?></span></div>
                            <?php endif; ?>

                            <?php if ($templateType): ?>
                                <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                            <?php endif; ?>

                            <?php if ($description):?>
                                <div class="product-item-description">
                                    <?= /* @noEscape */ $_helper->productAttribute($_item, $_item->getShortDescription(), 'short_description') ?>
                                    <a title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="action more"><?= $block->escapeHtml(__('Learn More')) ?></a>
                                </div>
                            <?php endif; ?>

                            <?php if ($showCart): ?>
                                <div class="product-action-wrapper">
                                    <?php if ($_item->isSaleable()): ?>
                                        <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)): ?>
                                            <button class="action tocart primary btn-cart"
                                                    data-mage-init='{"redirectUrl":{"url":"<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}'
                                                    type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                <i class="meigee-icon-cart"></i><span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        <?php else: ?>
                                            <?php
                                            $postDataHelper = $this->helper(Magento\Framework\Data\Helper\PostHelper::class);
                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                            ?>
                                            <button class="action tocart primary btn-cart"
                                                    data-post='<?= /* @noEscape */ $postData ?>'
                                                    type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                <i class="meigee-icon-cart"></i><span><?php $block->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <a href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" title="<?php echo __('Read more') ?>" class="btn btn-default btn-cart"><i class="meigee-icon-read-more"></i><span><?php echo __('Read more') ?></span></a>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>

                            <?php if ($showCompare): ?>
                                <div class="secondary-actions-wrapper" data-role="add-to-links">
                                    <?php if ($block->getAddToCompareUrl()): ?>
                                        <?php $compareHelper = $this->helper(Magento\Catalog\Helper\Product\Compare::class); ?>
                                        <a href="#" class="action tocompare"
                                           title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>"
                                           data-post='<?= /* @escapeNotVerified */ $compareHelper->getPostDataParams($_item) ?>'>
                                            <i class="meigee-icon-compare"></i>
                                        </a>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                        <?= ($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
