<?php
use Magento\Framework\App\Action\Action;

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var $productLabels \Meigee\Sirena\ViewModel\ProductLabels
 * @var $scopeConfig \Meigee\Sirena\ViewModel\ScopeConfig
 * @var $themeConfigPhp \Meigee\Sirena\ViewModel\ThemeConfigPhp
 * @var $enabledModuleCheck \Meigee\Sirena\ViewModel\EnabledModuleCheck
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
 
$_productCollection = $block->getLoadedProductCollection()->addMediaGalleryData();
$_helper = $this->helper(\Magento\Catalog\Helper\Output::class);
 if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php echo $block->escapeHtml(__('We can\'t find products matching the selection.')); ?></div></div>
<?php else:
    echo $block->getToolbarHtml();
    echo $block->getAdditionalHtml();

     $scopeConfig = $block->getScopeConfig();
     $themeConfigPhp = $block->getThemeConfigPhp();
     $enabledModuleCheck = $block->getEnabledModuleCheck();
     $productsWrapperClass = 'products wrapper';
     $customSwitcherEnabled = $themeConfigPhp->getGridSwitcherCustom();
     $customHoverEnabled = $themeConfigPhp->getProductCustomHover();
     $productHoverType = $themeConfigPhp->getProductHoverType();
     $lightboxEnabled = $themeConfigPhp->getLightbox();
     $lightboxListingEnabled = $themeConfigPhp->getLightboxListing();
     $showProductName = $themeConfigPhp->getProductShowName();
     $showProductPrice = $themeConfigPhp->getProductShowPrice();
     $showCartBtn = $themeConfigPhp->getProductShowAddtocart();
     $showCompareBtn = $themeConfigPhp->getProductShowCompareBtn();
     $showWishlistBtn = $themeConfigPhp->getProductShowWishlistBtn();
     $showStockStatus = $themeConfigPhp->getProductShowStockStatus();
     $quickviewModuleEnabled = $enabledModuleCheck->isModuleEnabled('WeltPixel_Quickview');
     $quickviewEnabled = $scopeConfig->getConfig('weltpixel_quickview/general/enable_product_listing');
     $showQuickviewBtn = $themeConfigPhp->getProductShowQuickviewBtn();
     $labelsType = $themeConfigPhp->getLabelsType();
     $isRTL = $themeConfigPhp->getSiteRtl();
     $showRatingStars = $themeConfigPhp->getProductShowStars();
     $productLabels = $block->getProductLabels();

     if ($block->getMode() == 'grid' || $customSwitcherEnabled) {
         $viewMode = 'grid';
         $image = 'category_page_grid';
         $showDescription = false;
         $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
         $gridColumns = $themeConfigPhp->getGridSwitcherDefaultCols();
         $productsWrapperClass .= ' grid products-grid';
    } else {
         $viewMode = 'list';
         $image = 'category_page_list';
         $showDescription = true;
         $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
         $gridColumns = 'columns-1';
         $productsWrapperClass .= ' list products-list';
    }
    if ( $customHoverEnabled ) {
         if ( $themeConfigPhp->getProductCustomHoverType() ) {
             $productsWrapperClass .= ' hover-scale';
         } else {
             $productsWrapperClass .= ' hover-simple';
         }
    }
    $productsWrapperClass .= ' product-hover-'.$productHoverType.' '.$labelsType.' '.$gridColumns;
  	if ( !$showCartBtn ) {
  	    $productsWrapperClass .= ' no-cart-button';
  	}
  	if ( !$showWishlistBtn ) {
  	    $productsWrapperClass .= ' no-wishlist-button';
  	}
    if ( $customSwitcherEnabled ) {
        $productsWrapperClass .= ' custom-grid-enabled';
    }
    ?>

    <div class="<?php echo $block->escapeHtmlAttr($productsWrapperClass); ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php echo $block->getChildHtml('meigee-listing-block'); ?>
            <?php foreach ($_productCollection as $_product):
                $productImage = $block->getImage($_product, $image, array('data-hover-image'=>null));
                $productInnerWrapperClass = 'product-item-info product-item-details';
                if ( !$_product->isAvailable() ) {
                    $productInnerWrapperClass .= ' sold-out';
                }
                $images = $_product->getMediaGalleryImages();
                if ( !$customHoverEnabled && ($images->count() > 1) ) {
                    $productInnerWrapperClass .= ' with-carousel';
                } ?>
                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="<?php echo $block->escapeHtmlAttr($productInnerWrapperClass); ?>" data-container="product-grid">
                    <?php // Product Image ?>
                    <div class="image-wrapper">
                        <?php if ( !$customHoverEnabled ) {
                            if ($images->count() > 1) {
                                $swiperDots = false;
                                $swiperRtlClass = '';
                                if ($images->count() <=4) { $swiperDots = 'true'; }
                                if ($isRTL && $isRTL!='') { $swiperRtlClass = ' swiper-container-rtl'; } ?>
                                <div class="swiper-container<?= $block->escapeHtmlAttr($swiperRtlClass) ?>" data-swiper-dots="<?= $block->escapeHtmlAttr($swiperDots) ?>">
                                    <div class="more-views swiper-wrapper">
                                        <?php foreach ($images as $gallery_image) { ?>
                                            <a href="<?php echo $block->escapeUrl($_product->getProductUrl()); ?>" class="product photo swiper-slide">
                                                <?php $imgHelper = $this->helper('Magento\Catalog\Helper\Image')->init($_product, $image)->setImageFile($gallery_image['file']);
                                                $imgUrl = $imgHelper->getUrl();
                                                $imgWidth = $imgHelper->getWidth();
                                                $imgHeight = $imgHelper->getHeight();
                                                $imgAlt = $imgHelper->getLabel();
                                                $imgSwatchRenderClass = '';
                                                if ($_product->getSmallImage() === $gallery_image['file']) {
                                                    $imgSwatchRenderClass = ' product-image-photo';
                                                }
                                                ?>
                                                    <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" class="photo product lazyload<?= $block->escapeHtmlAttr($imgSwatchRenderClass) ?>"
                                                         data-src="<?= $block->escapeUrl($imgUrl) ?>"
                                                         width="<?= $block->escapeHtmlAttr($imgWidth) ?>"
                                                         height="<?= $block->escapeHtmlAttr($imgHeight) ?>"
                                                         alt="<?= $block->escapeHtmlAttr($imgAlt) ?>" />
                                            </a>
                                        <?php } ?>
                                    </div>
                                    <?php if ($swiperDots){ echo '<div class="swiper-pagination"></div>'; } ?>
                                    <div class="swiper-button-prev"></div>
                                    <div class="swiper-button-next"></div>
                                </div>
                            <?php } else { ?>
                                    <a href="<?= $block->escapeUrl($_product->getProductUrl()); ?>" class="product photo product-item-photo">
                                        <?= $productImage->toHtml() ?>
                                    </a>
                            <?php } ?>
                        <?php } else {
                            $hoverImage = $_product->getHoverImage();
                            if ($hoverImage) {
                                $hoverImageUrl = $this->helper('Magento\Catalog\Helper\Image')
                                    ->init($_product, $image)
                                    ->setImageFile($hoverImage)
                                    ->getUrl();
                                $productImage = $block->getImage($_product, $image, array('data-hover-image'=>$hoverImageUrl));
                            } ?>
                            <a href="<?php echo $block->escapeUrl($_product->getProductUrl()); ?>" class="product photo product-item-photo" tabindex="-1">
                                <?php echo $productImage->toHtml(); ?>
                            </a>
                        <?php } ?>
                        <?php if (!$_product->isAvailable()): ?>
                            <div class="sold-out-label">
                                <span><?php echo $block->escapeHtml(__('Sold out')); ?></span>
                            </div>
                        <?php endif; ?>
                    </div>

                    <!--Product Labels-->
                    <?php if($productLabels->getProductNew($_product)): ?>
                        <span class="product-labels label-new"><?= $block->escapeHtml(__('Label new')) ?></span>
                    <?php endif; ?>
                    <?php if ($productLabels->getProductOnlyLeft($_product)): ?>
                        <span class="product-labels label-sale availability-only">
                            <i class="meigee-icon-arrow-left"></i><?= $productLabels->getProductOnlyLeft($_product); ?>
                            <strong><?= $block->escapeHtml(__('Left')) ?></strong>
                        </span>
                    <?php endif; ?>
                    <?php if ($productLabels->getProductSalePercent($_product)):
                        echo sprintf(__('<span class="product-labels label-sale percentage">%s off</span>'), $productLabels->getProductSalePercent($_product).'%');
                    endif; ?>
                    <?php if ($productLabels->getProductSale($_product)): ?>
                        <span class="product-labels label-sale"><?= $block->escapeHtml(__('Label sale')) ?></span>
                    <?php endif; ?>

                    <?php // Product Title
                    $_productNameStripped = '';
                    if($showProductName){
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php echo $block->escapeUrl($_product->getProductUrl()); ?>">
                                <?php echo $block->escapeHtml($_helper->productAttribute($_product, $_product->getName(), 'name')); ?>
                            </a>
                        </strong>
                    <?php } ?>

                    <?php // Wishlist
                    if( $showWishlistBtn && $this->helper('Magento\Wishlist\Helper\Data')->isAllow() ){ ?>
                        <div data-role="add-to-links" class="add-to-links wishlist-button-wrapper">
                            <a href="#" data-post='<?= $block->escapeHtmlAttr($block->getAddToWishlistParams($_product)); ?>' class="action towishlist" data-action='add-to-wishlist' title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"><span><?= $block->escapeHtml(__('Add to Wish List')) ?></span></a>
                        </div>
                    <?php } ?>

                    <?php // Product Price
                    if( $showProductPrice ) {
                        /* @noEscape */ echo $block->getProductPrice($_product);
                    } ?>

                    <?php // Product Availability
                    if($showStockStatus) {
                        if ($_product->isAvailable()): ?>
                            <div class="stock available"><span><?php echo $block->escapeHtml(__('In stock')) ?></span></div>
                        <?php else: ?>
                            <div class="stock unavailable"><span><?php echo $block->escapeHtml(__('Out of stock')) ?></span></div>
                        <?php endif;
                    } ?>

                    <?php // Reviews
                    if ($showRatingStars) {
                        echo $block->getReviewsSummaryHtml($_product, $templateType);
                    } ?>

                    <?php // Description
                    if ( $showDescription ) { ?>
                        <div class="product description product-item-description">
                            <?php /* @noEscape */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                            <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" title="<?php /* @noEscape */ echo $_productNameStripped ?>"
                               class="action more"><?php echo $block->escapeHtml(__('Learn More')) ?></a>
                        </div>
                    <?php } ?>

                    <?php // Product Timer
                    if ($productTimer = $block->getChildBlock('meigee.product.timer.wrapper')) {
                        echo $productTimer->setProduct($_product)->getChildHtml();
                    } ?>

                    <?php // Product Options
                    if ($block->getProductDetailsHtml($_product)) {
                        echo '<div class="product-details-wrapper">'.$block->getProductDetailsHtml($_product).'</div>';
                    } ?>

                    <?php // Add to cart
                    if( $showCartBtn ){ ?>
                        <div class="product-action-wrapper">
                            <?php if ($_product->isSaleable()): ?>
                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                    <input type="hidden" name="product" value="<?php /* @noEscape */ echo $postParams['data']['product']; ?>">
                                    <input type="hidden" name="<?php /* @noEscape */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @noEscape */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                    <?php echo $block->getBlockHtml('formkey')?>
                                    <button type="submit"
                                            title="<?php echo $block->escapeHtmlAttr(__('Add to Cart')); ?>"
                                            class="action tocart btn-cart">
                                        <i class="meigee-icon-cart"></i><span><?php echo $block->escapeHtml(__('Add to Cart')); ?></span>
                                    </button>
                                </form>
                            <?php else: ?>
                                <a href="<?php echo $block->escapeUrl($_product->getProductUrl()); ?>" title="<?php echo $block->escapeHtml(__('Read more')); ?>" class="btn-cart btn"><i class="meigee-icon-read-more"></i><span><?php echo $block->escapeHtml(__('Read more')); ?></span></a>
                            <?php endif; ?>
                        </div>
                    <?php } ?>

                    <?php // Secondary Action Buttons
                    if ( $showCompareBtn || ($showQuickviewBtn && $quickviewEnabled && $quickviewModuleEnabled) || ($lightboxEnabled && $lightboxListingEnabled) ) { ?>
                    <div class="secondary-actions-wrapper add-to-links" data-role="add-to-links">
                        <?php if ($showCompareBtn && $block->getAddToCompareUrl()): ?>
                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                            <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_product) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                <i class="meigee-icon-compare"></i>
                            </a>
                        <?php endif; ?>

                        <?php if($showQuickviewBtn && $quickviewEnabled && $quickviewModuleEnabled){ ?>
                            <a href="javascript: void(0);" data-quickview-url="<?php echo $block->escapeUrl($block->getBaseUrl()); ?>weltpixel_quickview/catalog_product/view/id/<?php echo $block->escapeHtml($_product->getEntityId()); ?>" class="weltpixel-quickview" title="<?= $block->escapeHtmlAttr(__('Quickview')) ?>"><i class="meigee-icon-quickview"></i><span><?php echo $block->escapeHtml(__('Quick view')); ?></span></a>
                        <?php } ?>

                        <?php if($lightboxEnabled && $lightboxListingEnabled){ ?>
                            <a href="<?php echo $block->escapeUrl($productImage->getImageUrl());  ?>" class="lightbox-button"  data-toggle="lightbox" data-footer="<?php echo $block->escapeHtmlAttr($_helper->productAttribute($_product, $_product->getName(), 'name')); ?>" title="<?= $block->escapeHtmlAttr(__('Show in Lightbox')) ?>">
                                <i class="meigee-icon-zoom"></i>
                            </a>
                        <?php } ?>
                    </div>
                    <?php } ?>
                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>

     <?php echo '<div class="bottom-toolbar">'.$block->getToolbarHtml().'</div>'; ?>
     <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
                "[data-role=tocart-form], .form.map.checkout": {
                    "catalogAddToCart": {
                        "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                    }
                }
            }
        </script>
     <?php endif; ?>

     <script type="text/x-magento-init">
        {
            <?php if ($customSwitcherEnabled) : ?>
            ".toolbar .modes": {
                "Meigee_Sirena/js/theme_grid_switcher":{}
            },
            <?php endif; ?>
            "*": {
                "Meigee_Sirena/js/theme_listing_helper":{}
            }
        }
    </script>

<?php endif; ?>
