<?php
/**
 * @var $block \Magento\Checkout\Block\Cart\Sidebar
 * @var $themeConfigPhp \Meigee\Sirena\ViewModel\ThemeConfigPhp
 */

$themeConfigPhp = $block->getThemeConfigPhp();
$icon_status = $themeConfigPhp->getMinicartShowIcon();
$text_status = $themeConfigPhp->getMinicartShowText();
$counter_status = $themeConfigPhp->getMinicartShowCounter();
?>
<?php if($icon_status || $text_status || $counter_status) { ?>
    <div data-block="minicart" class="minicart-wrapper">
        <a class="action showcart title-cart<?php if ($text_status): echo ' with-text'; endif; ?>" href="<?php echo $block->escapeUrl($block->getShoppingCartUrl()); ?>"
           data-bind="scope: 'minicart_content'">
            <span class="counter qty empty"
                      data-bind="css: { empty: !!getCartParam('summary_count') == false && !isLoading() }, blockLoader: isLoading">
                <span class="icon-wrapper">
                    <?php if($icon_status) { ?>
                        <span class="icon">
                            <i class="meigee-icon-cart"></i>
                        </span>
                    <?php } ?>
                    <?php if($text_status) { ?>
                        <span class="text"><?php echo $block->escapeHtml(__('My Bag')); ?></span>
                    <?php } ?>
                    <?php if($counter_status) { ?>
                        <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
                        <span class="counter-label">
                            <!-- ko if: getCartParam('summary_count') -->
                                <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                                <!-- ko i18n: 'items' --><!-- /ko -->
                            <!-- /ko -->
                        </span>
                    <?php } ?>
                </span>
            </span>
        </a>
        <?php if ($block->getIsNeedToDisplaySideBar()): ?>
            <div class="block block-minicart empty"
                 data-role="dropdownDialog"
                 data-mage-init='{"dropdownDialog":{
                    "appendTo":"[data-block=minicart]",
                    "triggerTarget":".showcart",
                    "timeout": "2000",
                    "closeOnMouseLeave": true,
                    "closeOnEscape": true,
                    "triggerClass":"active",
                    "parentClass":"active",
                    "buttons":[]}}'>
                <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                </div>
    			<?php echo $block->getChildHtml('minicart.addons'); ?>
            </div>
        <?php else: ?>
            <script>
                require(['jquery'], function ($) {
                    $('a.action.showcart').click(function() {
                        $(document.body).trigger('processStart');
                    });
                });
            </script>
        <?php endif ?>
        <script>window.checkout = <?= /* @noEscape */ $block->getSerializedConfig(); ?>;</script>
        <script type="text/x-magento-init">
        {
            "[data-block='minicart']": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            },
            "*": {
                "Magento_Ui/js/block-loader": "<?= $block->escapeJs($block->getViewFileUrl('images/loader-1.gif')) ?>"
            }
        }
        </script>
    </div>
<?php } ?>
