<?php
/**
 * @var \Magento\Store\Block\Switcher $block
 * @var $themeConfigPhp \Meigee\Sirena\ViewModel\ThemeConfigPhp
 */
?>
<?php if (count($block->getStores())>1) : ?>
    <?php /* Custom Sirena options */
    $themeConfigPhp = $block->getThemeConfigPhp();
    $label = $themeConfigPhp->getLangSwitcherShowLabel();
    $languages = $themeConfigPhp->getLangSwitcherType(); ?>

    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
<div class="dropdown-item language">
    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">
        <?php if($label) { ?>
            <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Language')) ?></span></strong>
        <?php } ?>
        <?php if($languages == 'language_flags') { ?>
            <div class="actions options switcher-options">
                <ul class="form-languages language-flags">
                    <?php foreach ($block->getStores() as $_lang): ?>
                        <?php if ($_lang->getId() != $block->getCurrentStoreId()) : ?>
                            <li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> switcher-option">
                                <a href="<?= $block->escapeUrl($block->getViewModel()->getTargetStoreRedirectUrl($_lang)) ?>">
                                    <img src="<?php echo $block->getViewFileUrl('images').'/lang/'.$block->escapeHtml($_lang->getName()); ?>.jpg" alt="<?php echo $block->escapeHtml($_lang->getName()) ?>">
                                </a>
                            </li>
                        <?php else : ?>
                            <li class="view-<?php echo $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                                <span><img src="<?php echo $block->getViewFileUrl('images').'/lang/'.$block->escapeHtml($block->getStoreName()); ?>.jpg" alt="<?php echo $block->escapeHtml($block->getStoreName()) ?>"></span>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php } elseif($languages == 'language_list') { ?>
            <div class="actions options switcher-options">
                <ul class="form-languages language-list">
                    <?php foreach ($block->getStores() as $_lang): ?>
                        <?php if ($_lang->getId() != $block->getCurrentStoreId()) : ?>
                            <li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> switcher-option">
                                <a href="<?= $block->escapeUrl($block->getViewModel()->getTargetStoreRedirectUrl($_lang)) ?>">
                                    <?php echo $block->escapeHtml($_lang->getName()); ?>
                                </a>
                            </li>
                        <?php else : ?>
                            <li class="view-<?php echo $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                                <span><?php echo $block->getStoreName(); ?></span>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php } else { ?>
            <div class="actions dropdown options switcher-options">
                <div class="action toggle switcher-trigger"
                     id="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>"
                     data-mage-init='{"dropdown":{}}'
                     data-toggle="dropdown"
                     data-trigger-keypress-button="true">
                    <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                        <span><?= $block->escapeHtml($block->getStoreName()) ?></span>
                    </strong>
                </div>
                <ul class="dropdown switcher-dropdown"
                    data-target="dropdown">
                    <?php foreach ($block->getStores() as $_lang): ?>
                        <?php if ($_lang->getId() != $block->getCurrentStoreId()) : ?>
                            <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option">
                                <a href="<?= $block->escapeUrl($block->getViewModel()->getTargetStoreRedirectUrl($_lang)) ?>">
                                    <?= $block->escapeHtml($_lang->getName()) ?>
                                </a>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php } ?>
    </div>
</div>
<?php endif; ?>