<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Meigee\Sirena\Block\ProductWidget\Product\ProductsListExtended
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-footer-list';

    $mode = 'list';

    $image = 'new_products_content_widget_list_sm';
    $title = $block->getTitle() ? __( $block->getTitle() ) : '';
    $items = $block->getProductCollection()->getItems();

    //$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

    $widget_id = $block->getData( 'widget_id' );

    $_helper = $this->helper( 'Magento\Catalog\Helper\Output' );

    $showName = $block->getOptionVal( 'product_name' );
    $showPrice = $block->getOptionVal( 'product_price' );
    $showCart = $block->getOptionVal( 'add_to_cart' );
    $showWishlist = $block->getOptionVal( 'wishlist' );
    $showCompare = $block->getOptionVal( 'compare' );
    $showReviews = $block->getOptionVal( 'rating_stars_footer_list' );

    /* Additional Theme options */
    $lightboxStatus = $block->getPhpConfigLigtbox();
    $showLightbox = $block->getPhpConfigLigtboxHome();
    $showQuickview = $block->getPhpConfigQuickview();
    $isRTL = $block->getPhpConfigIsRtl();
    $labelsType = $block->getPhpConfigLabelsType();    
    $customImageHoverStatus = $block->getPhpConfigCustomHover();

    $products_wrapper_class = 'products-'.$mode.' '.$mode.' product-hover-2 '.$labelsType;

    if ( $customImageHoverStatus ) {
        if ( $block->getPhpConfigCustomHoverType() ) {
            $products_wrapper_class .= ' hover-scale';
        } else {
            $products_wrapper_class .= ' hover-simple';
        }
    }
    if ( !$showCart ) {
        $products_wrapper_class .= ' no-cart-button';
    }
    if ( !$showWishlist ) {
        $products_wrapper_class .= ' no-wishlist-button';
    }
} ?>

<?php if ($exist):?>
<div class="block widget block-products-list meigee-widget footer-list">
    <?php if ($title):?>
        <div class="block-title">
            <strong><?php echo $block->escapeHtml($title); ?></strong>
        </div>
    <?php endif ?>
    <div class="block-content">
        <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
        <div class="<?php echo $block->escapeHtmlAttr($products_wrapper_class); ?>">
            <ol class="product-items <?= $block->escapeHtmlAttr($type) ?>">
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item): ?>

                <?php /* Additional classes for product images */
                $product_inner_wrapper_class = 'product-item-info';
                $productImage = $block->getImage($_item, $image, array('data-hover-image'=>null));
                if ( !$_item->isAvailable() ) {
                    $product_inner_wrapper_class .= ' sold-out';
                }
                ?>

                <?php if ($iterator++ != 1) { ?></li><?php } ?>
                <li class="product-item">

                    <div class="<?php echo $block->escapeHtmlAttr($product_inner_wrapper_class); ?>">

                        <div class="image-wrapper">
                            <a href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product photo product-item-photo">
                                <?php
                                $hoverImage = $customImageHoverStatus ? $_item->getHoverImage() : false;
                                if ($hoverImage)
                                {
                                    $hoverImageUrl = $this->helper('Magento\Catalog\Helper\Image')
                                        ->init($_item, 'hover_image')
                                        ->setImageFile($hoverImage)
                                        ->getUrl();
                                    $productImage = $block->getImage($_item, $image, array('data-hover-image'=>$hoverImageUrl));
                                }
                                else
                                {
                                    $productImage = $block->getImage($_item, $image, array('data-hover-image'=>null));
                                }
                                echo $productImage->toHtml();
                                ?>
                            </a>

                            <?php if (!$_item->getIsSalable()): ?>
                                <div class="sold-out-label">
                                    <span><?php echo $block->escapeHtml(__('Sold out')); ?></span>
                                </div>
                            <?php endif; ?>
                        </div>

                        <!--Product Labels-->
                        <?php if($block->getProductNew($_item)): ?>
                            <span class="product-labels label-new"><?= $block->escapeHtml(__('Label new')) ?></span>
                        <?php endif; ?>
                        <?php if ($block->getProductOnlyLeft($_item)): ?>
                            <span class="product-labels label-sale availability-only">
                                    <i class="meigee-icon-arrow-left"></i><?= $block->getProductOnlyLeft($_item); ?>
                                <strong><?= $block->escapeHtml(__('Left')) ?></strong>
                                </span>
                        <?php endif; ?>
                        <?php if ($block->getProductSalePercent($_item)):
                            echo sprintf(__('<span class="product-labels label-sale percentage">%s off</span>'), $block->getProductSalePercent($_item).'%');
                        endif; ?>
                        <?php if ($block->getProductSale($_item)): ?>
                            <span class="product-labels label-sale"><?= $block->escapeHtml(__('Label sale')) ?></span>
                        <?php endif; ?>

                        <?php if($showName) { ?>
                            <strong class="product-item-name">
                                <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                   href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                   class="product-item-link">
                                    <?= $block->escapeHtml($_item->getName()) ?>
                                </a>
                            </strong>
                        <?php } ?>

                        <?php echo ($showPrice ? $block->getProductPriceHtml($_item, $type) : ''); ?>

                        <?php if ($showReviews) {
                            echo $block->getReviewsSummaryHtml($_item, $templateType);
                        } ?>

                        <?php if ($showCart): ?>
                            <div class="product-action-wrapper">
                                <?php if ($_item->isSaleable()): ?>
                                    <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)): ?>
                                        <button class="action tocart primary btn-cart" data-mage-init='{"redirectUrl":{"url":"<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}' type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                            <i class="meigee-icon-cart"></i><span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                        </button>
                                    <?php else: ?>
                                        <?php
                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                        ?>
                                        <button class="action tocart primary btn-cart" data-post='<?= /* @noEscape */ $postData ?>' type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                            <i class="meigee-icon-cart"></i><span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                        </button>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <button class="action primary btn-cart" onclick="window.location.href='<?= $block->escapeUrl($block->getProductUrl($_item)) ?>'">
                                        <i class="meigee-icon-read-more"></i><span><?= $block->escapeHtml(__('View product')) ?></span>
                                    </button>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>

                        <?php if ($showCompare || ($lightboxStatus && $showLightbox) || ($showQuickview && $block->isQuickviewEnable())): ?>
                            <div class="secondary-actions-wrapper add-to-links" data-role="add-to-links">
                                <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                    <a href="#" class="action tocompare" data-post='<?php /* @noEscape */ echo $compareHelper->getPostDataParams($_item);?>' title="<?php echo $block->escapeHtmlAttr(__('Add to Compare')); ?>">
                                        <i class="meigee-icon-compare"></i><span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                    </a>
                                <?php endif; ?>

                                <?php if($showQuickview && $block->isQuickviewEnable()) { ?>
                                    <a href="javascript: void(0);" data-quickview-url="<?php echo $block->escapeUrl($block->getBaseUrl()); ?>weltpixel_quickview/catalog_product/view/id/<?php echo $block->escapeHtml($_item->getEntityId()); ?>" class="weltpixel-quickview" title="<?php echo $block->escapeHtmlAttr(__('Quickview')); ?>">
                                        <i class="meigee-icon-quickview"></i><span><?php echo $block->escapeHtml(__('Quick view')); ?></span>
                                    </a>
                                <?php } ?>

                                <?php if($lightboxStatus && $showLightbox){ ?>
                                    <a href="<?php echo $block->escapeUrl($block->getImage($_item, 'image_lightbox')->getImageUrl());  ?>" class="lightbox-button" data-toggle="lightbox" data-footer="<?php echo $block->escapeHtmlAttr($_item->getName()); ?>" title="<?php echo $block->escapeHtml(__('Lightbox')); ?>">
                                        <i class="meigee-icon-zoom"></i>
                                    </a>
                                <?php } ?>
                            </div>
                        <?php endif; ?>

                    </div>
                    <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
<?php endif;?>
