<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Review\Block\Product\Review $block */
?>
<div id="product-review-container" data-role="product-review" class="<?php echo $block->getCollectionSize() > 0 ? '' : 'is-empty'; ?>"></div>
<?= $block->getChildHtml() ?>
<script type="text/javascript">
    require(['jquery'], function ($){
        $.ajax({
            url: "<?= $block->escapeJs($block->escapeUrl($block->getProductReviewUrl())) ?>"
        }).done(function(html){
            $("#product-review-container").append(html);
        });
    });
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?= $block->escapeJs($block->escapeUrl($block->getProductReviewUrl())) ?>",
                "reviewsTabSelector": "#tab-label-reviews"
            },
            "Meigee_Sirena/js/theme_reviews": {
                "toggleText": "<?= $block->escapeJs($block->escapeHtml(('Roll up'))) ?>",
                "reviewsCount": "<?= $block->escapeJs($block->escapeHtml(( $block->getCollectionSize() ))) ?>"
            }
        }
    }
</script>