<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 * @var $themeConfigPhp \Meigee\Sirena\ViewModel\ThemeConfigPhp
 */

$themeConfigPhp = $block->getThemeConfigPhp();
 $openClass = '';
 $openItemClass = '';
 if ($themeConfigPhp->getOpenedLayeredNav() == 1) {
    $openClass = ' default-open';
    $openItemClass = ' active';
 } ?>
<?php if ($block->canShowBlock()): ?>
    <div class="block filter<?= $block->escapeHtmlAttr($openClass); ?>" id="layered-filter-block">
        <div class="block-title filter-title">
            <strong><?=  $block->escapeHtml(__('Shop By')); ?></strong>
        </div>
        <div class="block-content filter-content">
            <?= $block->getChildHtml('state') ?>
            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?= $block->escapeUrl($block->getClearUrl()); ?>" class="action clear filter-clear"><span><?= $block->escapeHtml(__('Clear All')); ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
        <?php if (!$wrapOptions): ?>
            <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?= $block->escapeHtml(__('Shopping Options')); ?></strong>
            <div class="filter-options" id="narrow-by-list">
                <?php $wrapOptions = true; endif; ?>
                <?php if ($filter->getItemsCount()): ?>
                <div data-role="collapsible" class="filter-options-item<?=$openItemClass?>">
                    <div role="heading" aria-level="3" class="filter-options-title"><?= $block->escapeHtml(__($filter->getName())) ?></div>
                    <div class="filter-options-content"><?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?></div>
                </div>
                <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($wrapOptions): ?>
            </div>
        <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
