<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog related posts template
 *
 * @var $block \Magefan\Blog\Block\Post\View\RelatedProducts
 */
?>

<?php
if ($exist = $block->getItems()->getSize() && $this->displayProducts()) {
    $type = 'related';
    $class = $type;

    $image = 'related_products_list';
    $title = __('Related Products');
    $items = $block->getItems();
    $limit = 0;
    $shuffle = 0;
    $canItemsAddToCart = true;

    $showWishlist = true;
    $showCompare = true;
    $showCart = false;
    $templateType = null;
    $description = false;
}
?>

<?php if ($exist):?>

    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?php echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
        <?php else: ?>
            <div class="block <?php echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?php echo $class; ?>">
    <?php endif; ?>
    <div class="block-title title">
        <strong id="block-<?php echo $class?>-heading" role="heading" aria-level="2"><?php echo $title; ?></strong>
    </div>
    <div class="block-content content" aria-labelledby="block-<?php echo $class?>-heading">


        <div class="products wrapper grid products-grid columns-4 products-<?php /* @escapeNotVerified */ echo $type; ?>">
            <ol class="products list items product-items">
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item): ?>
                    <?php $available = ''; ?>
                    <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                        <?php if (!$_item->getRequiredOptions()): ?>
                            <?php $available = 'related-available'; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($type == 'related' || $type == 'upsell'): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item" style="display: none;">' : '</li><li class="item product product-item swiper-slide" style="display: none;">' ?>
                    <?php else: ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item swiper-slide">' ?>
                    <?php endif; ?>
                    <div class="product-item-info <?php /* @escapeNotVerified */ echo $available; ?><?php echo !$_item->isAvailable() ? ' sold-out' : ''; ?>">
                        <div class="image-wrapper">
                            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                            </a>
                            <?php if (!$_item->isAvailable()): ?>
                                <div class="sold-out-label">
                                    <span><?php /* @escapeNotVerified */ echo __('Sold out') ?></span>
                                </div>
                            <?php endif; ?>
                        </div>

                        <?php // Product Title ?>
                        <strong class="product name product-item-name"><a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>">
                                <?= $block->escapeHtml($_item->getName()) ?></a>
                        </strong>

                        <?php // Wishlist
                        if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist) { ?>
                            <div data-role="add-to-links" class="add-to-links wishlist-button-wrapper">
                                <a href="#" data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist btn" data-action='add-to-wishlist' title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"><span><?= $block->escapeHtmlAttr(__('Add to Wish List')) ?></span></a>
                            </div>
                        <?php } ?>

                        <?php // Product Price
                        echo $block->getProductPrice($_item); ?>

                        <?php if ($templateType) { ?>
                            <?php echo $block->getReviewsSummaryHtml($_item, $templateType, true) ?>
                        <?php } ?>

                        <?php if($showCart): ?>
                            <div class="product-action-wrapper">
                                <?php if ($_item->isSaleable()): ?>
                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                        <button class="btn btn-cart action tocart primary"
                                                data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                            <i class="meigee-icon-cart"></i><span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                        </button>
                                    <?php else: ?>
                                        <?php
                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                        ?>
                                        <button class="btn btn-cart primary"
                                                data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                            <i class="meigee-icon-cart"></i><span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                        </button>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php echo __('Read more') ?>" class="btn btn-cart"><i class="meigee-icon-read-more"></i><span><?php echo __('Read more') ?></span></a>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                    <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
<?php endif;?>