<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Cookie\Block\Html\Notices $block */
?>
<?php if ($this->helper(\Magento\Cookie\Helper\Cookie::class)->isCookieRestrictionModeEnabled()) : ?>
    <div role="alertdialog"
         tabindex="-1"
         class="message global cookie"
         id="notice-cookie-block"
         style="display: none;">
        <div role="document" class="content" tabindex="0">
            <h3><?= $block->escapeHtml(__('Your privacy')) ?></h3>
            <p><?= $block->escapeHtml(__('This website requires cookies to provide all of its features. For more information on what data is contained in the cookies, please see our ')) ?>
                <?= $block->escapeHtml(__('<a href="%1">Privacy Policy page</a>', $block->getPrivacyPolicyLink()), ['a']) ?>.
            </p>
            <p><?= $block->escapeHtml(__('To accept cookies from this site, please click the Allow button below.')) ?></p>
            <div class="actions">
                <button id="btn-cookie-allow" class="action allow primary">
                    <span><?= $block->escapeHtml(__('Allow Cookies')) ?></span>
                </button>
            </div>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "#notice-cookie-block": {
                "cookieNotices": {
                    "cookieAllowButtonSelector": "#btn-cookie-allow",
                    "cookieName": "<?= /* @noEscape */ \Magento\Cookie\Helper\Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>",
                    "cookieValue": <?= /* @noEscape */ $this->helper(\Magento\Cookie\Helper\Cookie::class)->getAcceptedSaveCookiesWebsiteIds() ?>,
                    "cookieLifetime": <?= /* @noEscape */ $this->helper(\Magento\Cookie\Helper\Cookie::class)->getCookieRestrictionLifetime() ?>,
                    "noCookiesUrl": "<?= $block->escapeJs($block->escapeUrl($block->getUrl('cookie/index/noCookies'))) ?>"
                }
            }
        }
    </script>
<?php endif; ?>