<?php
$contentWidth = $block->getData('theme_config_php')->getSiteWidth();
$sticky_opacity = $block->getData('theme_config_php')->getHeaderStickyOpacity();
?>
<link rel="preload" href="<?php echo $block->escapeUrl($block->getViewFileUrl('fonts/OpenSans-Regular.woff2')); ?>" as="font" type="font/woff2" crossorigin="" />
<link rel="preload" href="<?php echo $block->escapeUrl($block->getViewFileUrl('fonts/Roboto-Regular.woff2')); ?>" as="font" type="font/woff2" crossorigin="" />
<link rel="preload" href="<?php echo $block->escapeUrl($block->getViewFileUrl('fonts/meigee-icons.woff2')); ?>" as="font" type="font/woff2" crossorigin="" />
<style type="text/css">.header-boxed .header-wrapper,.content-boxed .page-main,.content-boxed-content .page-main,.footer-boxed .page-footer,.container,.content-boxed .breadcrumbs>ul.items,.content-boxed .breadcrumbs,.content-boxed-content .breadcrumbs>ul.items,.page-header-inner .menu-wrapper .toggle-nav{max-width:<?php echo $block->escapeHtmlAttr($contentWidth); ?>px;width:100%;margin:0 auto;}.page-header.sticky-header {opacity:<?php echo $block->escapeHtmlAttr($sticky_opacity/100); ?>;}</style>
