<?php $welcomeMessage = $block->getWelcome(); ?>
<?php if (strlen(trim($welcomeMessage)) > 0):  ?>
    <p class="welcome" data-bind="scope: 'customer'">
        <!-- ko if: customer().fullname  -->
        <span data-bind="text: new String('<?php echo $block->escapeHtml(__('Welcome, %1!', '%1'));?>').replace('%1', customer().firstname)"></span>
        <!-- /ko -->
        <!-- ko ifnot: customer().fullname  -->
        <span data-bind="html:'<?=$block->escapeHtml($welcomeMessage) ?>'"></span>
        <!-- /ko -->
    </p>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer": {
                        "component": "Magento_Customer/js/view/customer"
                    }
                }
            }
        }
    }
    </script>
<?php endif ?>
