<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Meigee\ProductWidget\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = $block->getTitle() ? __( $block->getTitle() ) : '';
    $items = $block->getProductCollection()->getItems();

    // $templateType =  \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

    $productsPerRow = $block->getProductsPerRow();
    $widget_id = $block->getWidgetId();
    if ( isset( $widget_id ) ) {
        $type_price = 'widget-product-grid-' . $widget_id;
    } else {
        $type_price = $type;
    }
    $_helper = $this->helper( 'Magento\Catalog\Helper\Output' );

    $showName = $block->getOptionVal( 'product_name' );
    $showPrice = $block->getOptionVal( 'product_price' );
    $showStock = $block->getOptionVal( 'stock_status_grid' );
    $showDesc = $block->getOptionVal( 'desc_grid' );
    $showTimer = $block->getOptionVal( 'timer_grid' ); // TODO: add countdown to products
    $showCart = $block->getOptionVal( 'add_to_cart' );
    $showWishlist = $block->getOptionVal( 'wishlist' );
    $showCompare = $block->getOptionVal( 'compare' );
    $showRatingStars = $block->getOptionVal( 'rating_stars_grid' );
    $showRatingCustLink = $block->getOptionVal( 'rating_cust_link_grid' );
    $showAddReview = $block->getOptionVal( 'rating_add_review_link_grid' );
    ( ( $showRatingStars || $showRatingCustLink || $showAddReview ) ? $showReviews = true : $showReviews = false );
}
?>

<?php if ($exist):?>
    <div class="block widget block-products-list meigee-widget <?= /* @noEscape */ $mode ?>">
        <?php if ($block->getTitle()): ?>
        <div class="block-title">
            <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
        </div>
        <?php endif ?>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="product-items row <?= /* @noEscape */ $type ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php if ($iterator++ != 1): ?></li><?php endif ?>
                        <li class="product-item <?= /* @noEscape */ $block->getProductItemMediaCss() ?>">
                        <div class="product-item-info">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <div class="product-item-details">
                                <?php if($showName) { ?>
                                    <strong class="product-item-name">
                                        <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                           href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                           class="product-item-link">
                                            <?= $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </strong>
                                <?php } ?>

                                <?php echo ($showPrice ? $block->getProductPriceHtml($_item, $type) : ''); ?>

                                <?php if ($showReviews) {
                                    echo $block->getReviewsSummaryHtml($_item, $templateType);
                                } ?>

                                <?php if($showStock) { ?>
                                    <?php if ($_item->getIsSalable()): ?>
                                        <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                    <?php else: ?>
                                        <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                    <?php endif; ?>
                                <?php } ?>

                                <?php if ($showDesc):?>
                                    <div class="product-item-description">
                                        <?= /* @escapeNotVerified */ $_helper->productAttribute($_item, $_item->getShortDescription(), 'short_description') ?>
                                        <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                           href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>"
                                           class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                    </div>
                                <?php endif; ?>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-actions">
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart primary" data-mage-init='{"redirectUrl":{"url":"<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}' type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php
                                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary" data-post='<?= /* @noEscape */ $postData ?>' type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <button class="action primary" onclick="window.location.href='<?= $block->escapeUrl($block->getProductUrl($_item)) ?>'">
                                                        <span><?= $block->escapeHtml(__('View product')) ?></span>
                                                    </button>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($showWishlist || $showCompare): ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                    <a href="#"
                                                       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                    <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?= ($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
