<?php
/**
 * @var \Meigee\Sirena\ViewModel\ThemeConfigPhp $themeConfigPhp
 */

$themeConfigPhp = $block->getThemeConfigPhp();
$map_status = $themeConfigPhp->getContactMap();
$contactMapApi = $themeConfigPhp->getContactMapApi();
$map_latitude = $themeConfigPhp->getContactMapLatitude();
$map_longitude = $themeConfigPhp->getContactMapLongitude();
$map_zoom = $themeConfigPhp->getContactMapZoom();
$map_type = $themeConfigPhp->getContactMapType();
$map_marker = $themeConfigPhp->getContactMapMarker();
$map_marker_title = $themeConfigPhp->getContactMapMarkerText();
$map_block_status = $themeConfigPhp->getContactMapCustomInfo();
$map_block_static = $themeConfigPhp->getContactMapCustomInfoBlock();
$map_block_width = $themeConfigPhp->getContactMapCustomInfoWidth();
$map_block_height = $themeConfigPhp->getContactMapCustomInfoHeight();
$map_block_position = $themeConfigPhp->getContactMapCustomInfoPosition();
$random = rand(5, 1500);
if($map_status) {
    ?>
    <div class="map-body full-width">
        <div class="map-container">
            <?php if($map_block_status): ?>
                <div class="map-block<?php echo ' '.$map_block_position; ?>" style="width:<?php echo $map_block_width; ?>px; height:<?php echo $map_block_height; ?>px;">
                    <div class="indent">
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($map_block_static)->toHtml();?>
                    </div>
                </div>
            <?php endif; ?>
            <div id="map_canvas_<?php echo $random; ?>" class="map-wrapper"></div>
        </div>
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js<?php if($contactMapApi){ ?>?key=<?php echo $contactMapApi; } ?>"></script>
        <script type="text/javascript">
            require(["jquery"], function(jQuery) {
                //require(["googleMap"], function(backstretch) {

                function initialize_<?php echo $random; ?>(){
                    myLatlng = new google.maps.LatLng(<?php echo $map_latitude;?>, <?php echo $map_longitude;?>);
                    map_canvas = document.getElementById('map_canvas_<?php echo $random; ?>');
                    map_options = {
                        center: myLatlng,
                        zoom: <?php echo $map_zoom;?>,
                        mapTypeId: google.maps.MapTypeId.<?php echo $map_type;?>
                    }
                    map_<?php echo $random; ?> = new google.maps.Map(map_canvas, map_options)
                    <?php if($map_marker): ?>
                    marker = new google.maps.Marker({
                        position: myLatlng,
                        map: map_<?php echo $random; ?>,
                        title: '<?php echo $map_marker_title; ?>'
                    });
                    <?php endif; ?>
                }
                google.maps.event.addDomListener(window, 'load', initialize_<?php echo $random; ?>);
                parentBody = window.parent.document.getElementsByTagName('body');
                sizeMarker = 0;
                currentSize = jQuery(parentBody).width();
                if(currentSize < 480){currentSize = 1;}
                if(currentSize > 479 && currentSize < 768){currentSize = 2;}
                if(currentSize > 767 && currentSize < 977){currentSize = 3;}
                if(currentSize > 1279){currentSize = 4;}
                jQuery(window).resize(function(){
                    if (jQuery(parentBody).width() < 480) {
                        sizeMarker = 1;
                    }
                    if (jQuery(parentBody).width() > 479 && jQuery(parentBody).width() < 768) {
                        sizeMarker = 2;
                    }
                    if (jQuery(parentBody).width() > 767 && jQuery(parentBody).width() < 977){
                        sizeMarker = 3;
                    }
                    if (jQuery(parentBody).width() > 1279){
                        sizeMarker = 4;
                    }
                    if(currentSize != sizeMarker){
                        initialize_<?php echo $random; ?>();
                        currentSize = sizeMarker;
                    }
                });

                //});
            });
        </script>
    </div>
<?php } ?>
