<?php
/**
 * @var \Meigee\Sirena\ViewModel\ThemeConfigPhp $themeConfigPhp
 * @var $themeProductCountdown \Meigee\Sirena\ViewModel\ProductCountdown
 */

$themeConfigPhp = $block->getThemeConfigPhp();
$themeProductCountdown = $block->getThemeProductCountdown();
$timerStatus = $themeConfigPhp->getCountdown();
$timerListStatus = $themeConfigPhp->getCountdownListing();
$timerListDisplay = $themeConfigPhp->getCountdownListingType();
$timerProductStatus = $themeConfigPhp->getCountdownProduct();
$timerProductDisplay = $themeConfigPhp->getCountdownProductType();
$isProductPage = $themeProductCountdown->isProductPage();
$isCategoryPage = $themeProductCountdown->isCategoryPage();
$_product = false;
if ((bool)$timerStatus && (bool)$timerListStatus && $isCategoryPage) {
    $_product = $block->getProduct();
} elseif ((bool)$timerStatus && (bool)$timerProductStatus && $isProductPage) {
    $_product = $themeProductCountdown->getProduct();
}

if ($_product) {
    $specialPriceToDate = $_product->getSpecialToDate();
    $specialPrice = $_product->getSpecialPrice();
    $specialPriceFromDate = $_product->getSpecialFromDate();
    if($specialPriceToDate){
        $today = time();
        $rand = rand(1, 15000);
        $timerId = $_product->getId().$rand;
        if ($specialPrice && isset($specialPriceFromDate) && isset($specialPriceToDate)):
            if($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)): ?>

                <div class="timer-<?php echo $block->escapeHtmlAttr($timerId); ?> timer-box flip-timer <?php echo (($timerListDisplay == 0 && $current_page != 'catalog_product_view') || ($timerProductDisplay == 0 && $current_page == 'catalog_product_view') ? ' no-days' : ''); ?>">
                    <div class="timer-wrapper">
                        <div class="time-title"><?php echo $block->escapeHtml(__('Discount ends in:')); ?></div>
                        <div class="days flip-block">
                            <ul class="flip-items">
                                <li class="flip-item active"><span><span class="flip-wrapper flip-up"><span class="shadow"></span> <span class="flip-text">00</span></span><span class="flip-wrapper flip-down"><span class="shadow"></span><span class="flip-text">00</span></span></span></li>
                                <li class="flip-item before"><span><span class="flip-wrapper flip-up"><span class="shadow"></span><span class="flip-text">00</span></span><span class="flip-wrapper flip-down"><span class="shadow"></span><span class="flip-text">00</span></span></span></li>
                            </ul>
                            <span class="time-counter-descr"><?php echo $block->escapeHtml(__('Days')); ?></span>
                        </div>
                        <div class="flip-clock-divider"><span class="flip-clock-dot top"></span><span class="flip-clock-dot bottom"></span></div>
                        <div class="hours flip-block">
                            <ul class="flip-items">
                                <li class="flip-item active"><span><span class="flip-wrapper flip-up"><span class="shadow"></span><span class="flip-text">00</span></span><span class="flip-wrapper flip-down"><span class="shadow"></span><span class="flip-text">00</span></span></span></li>
                                <li class="flip-item before"><span><span class="flip-wrapper flip-up"><span class="shadow"></span><span class="flip-text">00</span></span><span class="flip-wrapper flip-down"><span class="shadow"></span><span class="flip-text">00</span></span></span></li>
                            </ul>
                            <span class="time-counter-descr"><?php echo $block->escapeHtml(__('Hours')); ?></span>
                        </div>
                        <div class="flip-clock-divider"><span class="flip-clock-dot top"></span><span class="flip-clock-dot bottom"></span></div>
                        <div class="minutes flip-block">
                            <ul class="flip-items">
                                <li class="flip-item active"><span><span class="flip-wrapper flip-up"><span class="shadow"></span><span class="flip-text">00</span></span><span class="flip-wrapper flip-down"><span class="shadow"></span><span class="flip-text">00</span></span></span></li>
                                <li class="flip-item before"><span><span class="flip-wrapper flip-up"><span class="shadow"></span><span class="flip-text">00</span></span><span class="flip-wrapper flip-down"><span class="shadow"></span><span class="flip-text">00</span></span></span></li>
                            </ul>
                            <span class="time-counter-descr"><?php echo $block->escapeHtml(__('Minutes')); ?></span>
                        </div>
                        <div class="flip-clock-divider"><span class="flip-clock-dot top"></span><span class="flip-clock-dot bottom"></span></div>
                        <div class="seconds flip-block">
                            <ul class="flip-items">
                                <li class="flip-item active"><span><span class="flip-wrapper flip-up"><span class="shadow"></span><span class="flip-text">00</span></span><span class="flip-wrapper flip-down"><span class="shadow"></span><span class="flip-text">00</span></span></span></li>
                                <li class="flip-item before"><span><span class="flip-wrapper flip-up"><span class="shadow"></span><span class="flip-text">00</span></span><span class="flip-wrapper flip-down"><span class="shadow"></span><span class="flip-text">00</span></span></span></li>
                            </ul>
                            <span class="time-counter-descr"><?php echo $block->escapeHtml(__('Seconds')); ?></span>
                        </div>
                    </div>
                </div>

                <script type="text/x-magento-init">
                {
                    "*": {
                        "Meigee_Sirena/js/theme_countdown_timer":
                        {
                            "endDate": "<?= $block->escapeHtml(Date("m/d/y", strtotime($specialPriceToDate)).' 11:59:00 PM') ?>",
                            "startDate": "<?= $block->escapeHtml(Date("m/d/y h:i:s A", strtotime($themeProductCountdown->getTodayDate()))) ?>",
                            "timerID": "<?= $block->escapeHtml($timerId) ?>"
                        }
                    }
                }
                </script>

            <?php
            endif;
        endif;
    }
} ?>
