<?php
/**
 * @var $block \Magento\Catalog\Block\Product\AbstractProduct
 * @var \Meigee\Sirena\ViewModel\ThemeConfigPhp $themeConfigPhp
 */
 
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Generic.WhiteSpace.ScopeIndent.Incorrect
?>

<?php
$items = array();
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = false;
            $showCart = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
			$price = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = false;
            $showCart = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
			$price = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
			$price = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
			$price = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('You May Also Like');
            $items = $block->getItemCollection();

            $showAddTo = false;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
			$price = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('You May Also Like');
            $items = $block->getItems();

            $showAddTo = false;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
			$price = true;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
			$price = false;
        }
    break;

    case 'other':
    break;
}
$rand = rand(100, 100000);
$themeConfigPhp = $block->getThemeConfigPhp();

/* Swiper Carousel for product lists */
$swiperType = 'small-only';
$swiperDesktopQty = $swiperTabletQty = 4;
$swiperNav = 'false';
if ( count($items) > 4) {
    $swiperType = 'product-slider';
}
?>

<?php if ($exist):?>

        <?php if ($type == 'crosssell' || $type == 'crosssell-rule'): ?>
            <div class="crosssell-wrapper">
        <?php endif; ?>
            <?php if ($type == 'related' || $type == 'upsell'): ?>
                <?php if ($type == 'related'): ?>
                    <div class="block <?= $block->escapeHtmlAttr($class) ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?= $block->escapeHtmlAttr($limit) ?>" data-shuffle="<?php /* @noEscape */ echo $shuffle; ?>">
                <?php else: ?>
                    <div class="block <?= $block->escapeHtmlAttr($class) ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
                <?php endif; ?>
            <?php else: ?>
                <div class="block <?php /* @escapeNotVerified */ echo $class; ?>">
            <?php endif; ?>
            <div class="block-title title">
                <strong id="block-<?= $block->escapeHtmlAttr($class) ?>-heading" role="heading" aria-level="2"><?php $block->escapeHtml($title) ?></strong>
            </div>
            <div class="block-content content" aria-labelledby="block-<?= $block->escapeHtmlAttr($class) ?>-heading">
                <?php if ($type == 'related' && $canItemsAddToCart): ?>
                    <div class="block-actions">
                        <?= $block->escapeHtml(__('Check items to add to the cart or')) ?>
                        <button type="button" class="action select" role="button"><span><?= $block->escapeHtml(__('select all')) ?></span></button>
                    </div>
                <?php endif; ?>

                <div class="products wrapper grid products-grid columns-4 products-<?= $block->escapeHtmlAttr($type) ?> swiper-container">
                    <ol class="products list items product-items swiper-wrapper">
                        <?php $iterator = 1; ?>
                        <?php foreach ($items as $_item): ?>
                        <?php $available = ''; ?>
                        <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                            <?php if (!$_item->getRequiredOptions()): ?>
                                <?php $available = 'related-available'; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if ($type == 'related' || $type == 'upsell'): ?>
                            <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item swiper-slide" style="display: none;">' : '</li><li class="item product product-item swiper-slide" style="display: none;">' ?>
                        <?php else: ?>
                            <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item swiper-slide">' : '</li><li class="item product product-item swiper-slide">' ?>
                        <?php endif; ?>
                        <div class="product-item-info <?php /* @noEscape */ echo $available; ?><?php echo !$_item->isAvailable() ? ' sold-out' : ''; ?>">
                            <div class="image-wrapper">
                                <?php /* @noEscape */ echo '<!-- ' . $image . '-->' ?>
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product photo product-item-photo">
                                    <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                </a>
                                <?php if (!$_item->isAvailable()): ?>
                                    <div class="sold-out-label">
                                        <span><?php /* @escapeNotVerified */ echo __('Sold out') ?></span>
                                    </div>
                                <?php endif; ?>
                            </div>

                            <?php // Product Title ?>
                            <strong class="product name product-item-name"><a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                <?= $block->escapeHtml($_item->getName()) ?></a>
                            </strong>

                            <?php // Wishlist
                            if( $this->helper('Magento\Wishlist\Helper\Data')->isAllow() ){ ?>
                                <div data-role="add-to-links" class="add-to-links wishlist-button-wrapper">
                                    <a href="#" data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist btn" data-action='add-to-wishlist' title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"><span><?= $block->escapeHtmlAttr(__('Add to Wish List')) ?></span></a>
                                </div>
                            <?php } ?>

                            <?php // Product Price
                    		if($price){
                    		    /* @noEscape */echo $block->getProductPrice($_item);
                    		}
                    		if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'){
                    		    /* @escapeNotVerified */ echo $block->getProductPrice($_item);
                    		} ?>

                    		<?php if ($templateType){ ?>
                                <?php echo $block->getReviewsSummaryHtml($_item, $templateType, true) ?>
                            <?php } ?>

                            <?php echo str_replace('grid', 'grid-'.$rand.'-product-'.$_item->getId().'', $_item->getProductPriceHtml($_item, $type)); ?>
                            <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'){ ?>
                                     <!-- <?php /* @escapeNotVerified */ // echo $block->getProductPrice($_item); ?> -->
                                     <?php if (!$_item->getRequiredOptions()){ ?>
                                          <div class="field choice related">
                                               <input type="checkbox" class="checkbox related" id="related-checkbox<?= $block->escapeHtmlAttr($_item->getId()) ?>" name="related_products[]" value="<?= $block->escapeHtmlAttr($_item->getId()) ?>" />
                                               <label class="label" for="related-checkbox<?php /* @escapeNotVerified */ echo $_item->getId() ?>"><span><?= $block->escapeHtml(__('Add to Cart')) ?></span></label>
                                          </div>
                                     <?php } ?>
                            <?php } ?>

                            <?php if($showCart): ?>
                                <div class="product-action-wrapper">
                                    <?php if ($_item->isSaleable()): ?>
                                        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                             <button class="btn btn-cart action tocart primary"
                                                                data-mage-init='{"redirectUrl":{"url":"<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                 <i class="meigee-icon-cart"></i><span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                             </button>
                                        <?php else: ?>
                                             <?php
                                                            $postDataHelper = $this->helper(\Magento\Framework\Data\Helper\PostHelper::class);
                                                            $postData = $postDataHelper->getPostData($block->escapeUrl($block->getAddToCartUrl($_item)), ['product' => $_item->getEntityId()])
                                             ?>
                                             <button class="btn btn-cart primary"
                                                                data-post='<?php /* @noEscape */ echo $postData; ?>'
                                                                type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                 <i class="meigee-icon-cart"></i><span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                             </button>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php echo __('Read more') ?>" class="btn btn-cart"><i class="meigee-icon-read-more"></i><span><?php echo __('Read more') ?></span></a>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                            <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                        <?php endforeach ?>
                    </ol>
                    <div class="swiper-pagination"></div>
                    <?php if ($swiperType == 'product-slider') {
                        $swiperNav = 'true'; ?>
                        <div class="swiper-button-prev"></div>
                        <div class="swiper-button-next"></div>
                    <?php } ?>
                </div>
            </div>
        <?php if ($type == 'crosssell' || $type == 'crosssell-rule'): ?>
            </div>
        <?php endif; ?>
    </div>
    <script type="text/x-magento-init">
        {
            ".swiper-container.products-<?= $block->escapeHtmlAttr($type) ?>": {
                "Meigee_Sirena/js/theme_carousel":{
                    "sliderType": "<?= $block->escapeHtmlAttr($swiperType) ?>",
                    "sliderItems": "<?= $block->escapeJs($swiperDesktopQty) ?>",
                    "sliderItemsTablet": "<?= $block->escapeJs($swiperTabletQty) ?>",
                    "pagination": true,
                    "loop": false,
                    "navigation": "<?= $block->escapeJs($swiperNav) ?>"
                }
            }
        }
    </script>
<?php endif;?>
