<?php
/**
 * Currency switcher
 *
 * @var \Magento\Directory\Block\Currency $block
 * @var \Meigee\Sirena\ViewModel\ThemeConfigPhp $themeConfigPhp
 */
?>
<?php if ($block->getCurrencyCount() > 1):
    $themeConfigPhp = $block->getThemeConfigPhp();
    $currencies = $block->getCurrencies();
    $currentCurrencyCode = $block->getCurrentCurrencyCode();
    $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '';
    /* custom_sirena: Extra Classes and helpers */
    $label = $themeConfigPhp->getCurrencySwitcherShowLabel();
    $currency_status = $themeConfigPhp->getCurrencySwitcherType();
    ?>
<div class="dropdown-item currency">
    <div class="switcher currency switcher-currency" id="switcher-currency<?= $block->escapeHtmlAttr($id) ?>">
        <?php if ($label) : ?>
            <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Currency')) ?></span></strong>
        <?php endif; ?>
        <?php if($currency_status == 'currency_images') : ?>
            <div class="actions options switcher-options">
                <ul class="form-currency">
                    <?php foreach ($currencies as $_code => $_name): ?>
                        <?php if ($_code != $currentCurrencyCode): ?>
                            <li class="currency-<?= $block->escapeHtmlAttr($_code) ?> switcher-option">
                                <a href="#" data-post='<?= /* @noEscape */ $block->getSwitchCurrencyPostData($_code) ?>'><?= $block->escapeHtml($_code) ?> - <?= $block->escapeHtml($_name) ?></a>
                            </li>
                        <?php else : ?>
                            <li class="currency-<?= $block->escapeHtml($block->getCurrentCurrencyCode()) ?>">
                                <span><?= $block->escapeHtml($currentCurrencyCode) ?> - <?= $currencies[$currentCurrencyCode] ? $block->escapeHtml($currencies[$currentCurrencyCode]) : '' ?></span>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php else : ?>
            <div class="actions dropdown options switcher-options">
                <div class="action toggle switcher-trigger"
                     id="switcher-currency-trigger<?= $block->escapeHtmlAttr($id) ?>"
                     data-mage-init='{"dropdown":{}}'
                     data-toggle="dropdown"
                     data-trigger-keypress-button="true">
                    <strong class="currency-<?= $block->escapeHtml($block->getCurrentCurrencyCode()) ?>">
                        <span><?= $block->escapeHtml($currentCurrencyCode) ?> - <?= $currencies[$currentCurrencyCode] ? $block->escapeHtml($currencies[$currentCurrencyCode]) : '' ?></span>
                    </strong>
                </div>
                <ul class="dropdown switcher-dropdown" data-target="dropdown">
                    <?php foreach ($currencies as $_code => $_name): ?>
                        <?php if ($_code != $currentCurrencyCode): ?>
                            <li class="currency-<?= $block->escapeHtmlAttr($_code) ?> switcher-option">
                                <a href="#" data-post='<?= /* @noEscape */ $block->getSwitchCurrencyPostData($_code) ?>'><?= $block->escapeHtml($_code) ?> - <?= $block->escapeHtml($_name) ?></a>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
