<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Meigee\Popup\ViewModel\Popup $popupViewModel
 */
$popupViewModel = $block->getPopupViewModel();

if ($popupViewModel->isCanShow()):
	$expires       = $popupViewModel->getPopupExpires();
	$popupWidth    = $popupViewModel->getPopupWidth();
	$popupHeight   = $popupViewModel->getPopupHeight();
?>
    <div class="modal fade popup-block"
         id="popup-block" tabindex="-1" role="dialog" aria-hidden="true" data-expires="<?php echo $expires; ?>"
         data-mage-init='{"meigeePopupSubscribe": {}}'
         style="display: none;">
    <div class="modal-dialog" style="width:<?php echo $popupWidth; ?>px;">
        <div class="modal-content" style="height: <?php echo $popupHeight; ?>px; width: <?php echo $popupWidth; ?>px; margin-top: -<?php echo ($popupHeight/2); ?>px;">
          <div class="modal-body">
              <?= $popupViewModel->getPopupStaticBlockHtml(); ?>
            <span class="popup-bottom"><input id="hide-subscribe-popup" type="checkbox"><label for="hide-subscribe-popup"><?php echo __('Don&#39;t show again'); ?></label></span>
          </div>
        </div>
      </div>
    </div>
<?php endif;?>
